# Generated by Django 5.0.3 on 2024-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_photostudio_book_photo_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
